import { useParams } from 'react-router-dom';
import { DetailPageShell } from '@/components/layout/DetailPageShell';
import { InvoicePreview } from '@/modules/billing/InvoicePreview';

export default function DealerInvoiceDetailPage() {
  const { id } = useParams();

  return (
    <DetailPageShell
      back={{ label: 'Dealer Invoices', href: '/admin/dealer-invoices' }}
      title="Dealer Invoice Details"
      subtitle="View customer bill generated by dealer"
    >
      <div className="mx-auto max-w-4xl p-2 bg-white rounded-xl shadow-sm border">
        <InvoicePreview id={id} />
      </div>
    </DetailPageShell>
  );
}
