import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Search, FileText } from 'lucide-react';
import { PageShell } from '@/components/layout/PageShell';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { LoadingState } from '@/components/feedback/LoadingState';
import { EmptyState } from '@/components/feedback/EmptyState';
import { invoicesService } from '@/services/invoices.service';
import { queryKeys } from '@/services/api/queryKeys';
import { formatCurrency } from '@/utils/format';

function Badge({ status }) {
  const map = {
    SENT: 'bg-blue-100 text-blue-700 border-blue-200',
    PAID: 'bg-green-100 text-green-700 border-green-200',
    CANCELLED: 'bg-red-100 text-red-700 border-red-200',
  };
  return (
    <span className={`inline-block rounded-full border px-2 py-0.5 text-xs font-semibold ${map[status] || 'bg-surface-2'}`}>
      {status}
    </span>
  );
}

function fmtDate(d) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

export default function DealerInvoiceListPage() {
  const navigate = useNavigate();
  const [search, setSearch] = useState('');

  const filters = { search: search || undefined, perPage: 50 };
  const { data, isLoading } = useQuery({
    queryKey: queryKeys.invoices.list(filters),
    queryFn: () => invoicesService.getList(filters),
  });

  const invoices = data?.data || [];

  return (
    <PageShell
      title="Dealer Invoices (Customer Bills)"
      subtitle="Invoices generated by dealers for retail customers"
    >
      <div className="flex flex-wrap gap-3 mb-4">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--color-text-tertiary)]" />
          <Input
            className="w-64 pl-9"
            placeholder="Search by invoice, dealer, customer…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
      </div>

      {isLoading ? <LoadingState message="Loading invoices…" /> : invoices.length === 0 ? (
        <EmptyState
          icon={FileText}
          title="No customer bills found"
          description="Dealer-to-customer retail bills will appear here"
        />
      ) : (
        <Card>
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b bg-surface-2 text-left text-xs uppercase text-[var(--color-text-secondary)]">
                    <th className="px-4 py-3">Invoice No</th>
                    <th className="px-4 py-3">Dealer</th>
                    <th className="px-4 py-3">Customer</th>
                    <th className="px-4 py-3">Date</th>
                    <th className="px-4 py-3 text-right">Total Amount</th>
                    <th className="px-4 py-3">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {invoices.map((inv) => (
                    <tr key={inv.id} className="border-b border-surface-3 hover:bg-surface-2 cursor-pointer" onClick={() => navigate(`/admin/dealer-invoices/${inv.id}`)}>
                      <td className="px-4 py-3 font-mono font-semibold text-brand-600">{inv.invoiceNo}</td>
                      <td className="px-4 py-3 font-medium">{inv.dealerName || '—'}</td>
                      <td className="px-4 py-3">{inv.customerName || '—'}</td>
                      <td className="px-4 py-3 text-[var(--color-text-secondary)]">{fmtDate(inv.issuedAt)}</td>
                      <td className="px-4 py-3 text-right tabular-nums font-semibold">{formatCurrency(inv.total)}</td>
                      <td className="px-4 py-3"><Badge status={inv.status} /></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}
    </PageShell>
  );
}
