export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh-token',
    me: '/auth/me',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  products: {
    list: '/products',
    detail: (id) => `/products/${id}`,
    tiers: (id) => `/products/${id}/tiers`,
    tier: (productId, tierId) => `/products/${productId}/tiers/${tierId}`,
    categories: '/products/categories/list',
  },
  inventory: {
    list: '/inventory',
    detail: (id) => `/inventory/${id}`,
    lowStock: '/inventory/low-stock',
    categories: '/inventory/categories',
    export: '/inventory/export',
    bulk: '/inventory/bulk',
  },
  warehouses: {
    list: '/warehouses',
    detail: (id) => `/warehouses/${id}`,
    stock: (id) => `/warehouses/${id}/stock`,
  },
  dispatch: {
    list: '/dispatch',
    detail: (id) => `/dispatch/${id}`,
    tracking: (id) => `/dispatch/${id}/tracking`,
    pending: '/dispatch/pending-count',
  },
  grn: {
    list: '/grn',
    detail: (id) => `/grn/${id}`,
  },
  customers: {
    list: '/customers',
    detail: (id) => `/customers/${id}`,
  },
  billing: {
    list: '/billing',
    detail: (id) => `/billing/${id}`,
    nextBillNumber: '/billing/next-bill-number',
    send: (id) => `/billing/${id}/send`,
    markPaid: (id) => `/billing/${id}/mark-paid`,
    cancel: (id) => `/billing/${id}/cancel`,
  },
  invoices: {
    list: '/invoices',
    detail: (id) => `/invoices/${id}`,
    pdf: (id) => `/invoices/${id}/pdf`,
  },
  gst: {
    config: '/gst/config',
    rates: '/gst/rates',
    hsn: '/gst/hsn',
    hsnLookup: (code) => `/gst/hsn/${code}`,
    validate: (gstin) => `/gst/validate/${gstin}`,
  },
  warranty: {
    list: '/warranty',
    detail: (id) => `/warranty/${id}`,
    eligibility: '/warranty/eligibility',
    claim: (id) => `/warranty/${id}/claim`,
  },
  complaints: {
    list: '/complaints',
    detail: (id) => `/complaints/${id}`,
    timeline: (id) => `/complaints/${id}/timeline`,
    openCount: '/complaints/open-count',
    escalate: (id) => `/complaints/${id}/escalate`,
    resolve: (id) => `/complaints/${id}/resolve`,
  },
  spares: {
    list: '/spares',
    detail: (id) => `/spares/${id}`,
    availability: (id) => `/spares/${id}/availability`,
    request: '/spares/request',
  },
  returns: {
    list: '/returns',
    detail: (id) => `/returns/${id}`,
    inspect: (id) => `/returns/${id}/inspect`,
  },
  dealers: {
    list: '/dealers',
    detail: (id) => `/dealers/${id}`,
    inventory: (id) => `/dealers/${id}/inventory`,
    team: (id) => `/dealers/${id}/team`,
    performance: (id) => `/dealers/${id}/performance`,
  },
  employees: {
    list: '/employees',
    detail: (id) => `/employees/${id}`,
    team: (managerId) => `/employees/team/${managerId}`,
    hierarchy: '/employees/hierarchy',
    reportingLine: (id) => `/employees/${id}/reporting-line`,
    dealers: {
      list: (id) => `/employees/${id}/dealers`,
      update: (id) => `/employees/${id}/dealers`,
    },
  },
  tasks: {
    list: '/tasks',
    detail: (id) => `/tasks/${id}`,
    pendingCount: '/tasks/pending-count',
  },
  approvals: {
    list: '/approvals',
    detail: (id) => `/approvals/${id}`,
    pendingCount: '/approvals/pending-count',
  },
  reports: {
    list: '/reports',
    catalog: '/reports/catalog',
    run: '/reports/run',
    preview: (code) => `/reports/preview/${code}`,
    detail: (id) => `/reports/${id}`,
  },
  orders: {
    list: '/orders',
    detail: (id) => `/orders/${id}`,
    tracking: (id) => `/orders/${id}/tracking`,
  },
  serviceRequests: {
    list: '/service-requests',
    detail: (id) => `/service-requests/${id}`,
  },
  analytics: {
    dashboard: (panel) => `/analytics/dashboard/${panel}`,
    revenue: '/analytics/revenue',
    orders: '/analytics/orders',
    complaints: '/analytics/complaints',
    inventory: '/analytics/inventory',
    dealers: '/analytics/dealers',
    kpis: '/analytics/kpis',
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    markRead: (id) => `/notifications/${id}/read`,
    markAllRead: '/notifications/read-all',
  },
  audit: {
    list: '/audit',
    detail: (id) => `/audit/${id}`,
  },
  settings: {
    general: '/settings/general',
    gst: '/settings/gst',
    notifications: '/settings/notifications',
    customerPortal: '/settings/customer-portal',
    caReports: '/settings/ca-reports',
    business: '/settings/business',
    businessBundle: '/settings/business/profile-bundle',
    invoice: '/settings/invoice',
    print: '/settings/print',
  },
  search: {
    global: '/search',
  },
  address: {
    pincode: (pin) => `/address/pincode/${pin}`,
    states: '/address/states',
  },
  upload: '/upload',
};
