export const queryKeys = {
  auth: {
    all: ['auth'],
    me: () => [...queryKeys.auth.all, 'me'],
    permissions: () => [...queryKeys.auth.all, 'permissions'],
  },
  products: {
    all: ['products'],
    lists: () => [...queryKeys.products.all, 'list'],
    list: (filters) => [...queryKeys.products.lists(), filters],
    details: () => [...queryKeys.products.all, 'detail'],
    detail: (id) => [...queryKeys.products.details(), id],
  },
  categories: {
    all: ['categories'],
    list: (filters) => [...queryKeys.categories.all, 'list', filters],
    detail: (id) => [...queryKeys.categories.all, 'detail', id],
  },
  brands: {
    all: ['brands'],
    list: (filters) => [...queryKeys.brands.all, 'list', filters],
    detail: (id) => [...queryKeys.brands.all, 'detail', id],
  },
  parties: {
    all: ['parties'],
    list: (filters) => [...queryKeys.parties.all, 'list', filters],
    detail: (id) => [...queryKeys.parties.all, 'detail', id],
  },
  purchases: {
    all: ['purchases'],
    list: (filters) => [...queryKeys.purchases.all, 'list', filters],
    detail: (id) => [...queryKeys.purchases.all, 'detail', id],
  },
  manufacture: {
    all: ['manufacture'],
    list: (filters) => [...queryKeys.manufacture.all, 'list', filters],
    detail: (id) => [...queryKeys.manufacture.all, 'detail', id],
    materials: (warehouseId) => [...queryKeys.manufacture.all, 'materials', warehouseId],
  },
  productTiers: {
    all: ['product-tiers'],
    list: (filters) => [...queryKeys.productTiers.all, 'list', filters],
    detail: (id) => [...queryKeys.productTiers.all, 'detail', id],
  },
  pricing: {
    all: ['pricing'],
    list: (filters) => [...queryKeys.pricing.all, 'list', filters],
    detail: (id) => [...queryKeys.pricing.all, 'detail', id],
  },
  expenses: {
    all: ['expenses'],
    list: (filters) => [...queryKeys.expenses.all, 'list', filters],
    detail: (id) => [...queryKeys.expenses.all, 'detail', id],
  },
  inventory: {
    all: ['inventory'],
    lists: () => [...queryKeys.inventory.all, 'list'],
    list: (filters) => [...queryKeys.inventory.lists(), filters],
    details: () => [...queryKeys.inventory.all, 'detail'],
    detail: (id) => [...queryKeys.inventory.details(), id],
    lowStock: () => [...queryKeys.inventory.all, 'low-stock'],
    categories: () => [...queryKeys.inventory.all, 'categories'],
  },
  stockMovements: {
    all: ['stock-movements'],
    list: (filters) => [...queryKeys.stockMovements.all, 'list', filters],
    skuHistory: (sku) => [...queryKeys.stockMovements.all, 'sku', sku],
  },
  warehouses: {
    all: ['warehouses'],
    lists: () => [...queryKeys.warehouses.all, 'list'],
    list: (filters) => [...queryKeys.warehouses.lists(), filters],
    details: () => [...queryKeys.warehouses.all, 'detail'],
    detail: (id) => [...queryKeys.warehouses.details(), id],
    stock: (id) => [...queryKeys.warehouses.detail(id), 'stock'],
  },
  dispatch: {
    all: ['dispatch'],
    lists: () => [...queryKeys.dispatch.all, 'list'],
    list: (filters) => [...queryKeys.dispatch.lists(), filters],
    details: () => [...queryKeys.dispatch.all, 'detail'],
    detail: (id) => [...queryKeys.dispatch.details(), id],
    pending: () => [...queryKeys.dispatch.all, 'pending-count'],
  },
  grn: {
    all: ['grn'],
    lists: () => [...queryKeys.grn.all, 'list'],
    list: (filters) => [...queryKeys.grn.lists(), filters],
    details: () => [...queryKeys.grn.all, 'detail'],
    detail: (id) => [...queryKeys.grn.details(), id],
  },
  customers: {
    all: ['customers'],
    list: (filters) => [...queryKeys.customers.all, 'list', filters],
    detail: (id) => [...queryKeys.customers.all, 'detail', id],
  },
  dealerDispatch: {
    all: ['dealer-dispatch'],
    list: (filters) => [...queryKeys.dealerDispatch.all, 'list', filters],
    detail: (id) => [...queryKeys.dealerDispatch.all, 'detail', id],
  },
  dealerGrn: {
    all: ['dealer-grn'],
    list: (filters) => [...queryKeys.dealerGrn.all, 'list', filters],
    detail: (id) => [...queryKeys.dealerGrn.all, 'detail', id],
  },
  dealerReports: {
    all: ['dealer-reports'],
    list: (filters) => [...queryKeys.dealerReports.all, 'list', filters],
  },
  billing: {
    all: ['billing'],
    lists: () => [...queryKeys.billing.all, 'list'],
    list: (filters) => [...queryKeys.billing.lists(), filters],
    details: () => [...queryKeys.billing.all, 'detail'],
    detail: (id) => [...queryKeys.billing.details(), id],
    nextBillNumber: () => [...queryKeys.billing.all, 'next-bill-number'],
  },
  invoices: {
    all: ['invoices'],
    lists: () => [...queryKeys.invoices.all, 'list'],
    list: (filters) => [...queryKeys.invoices.lists(), filters],
    details: () => [...queryKeys.invoices.all, 'detail'],
    detail: (id) => [...queryKeys.invoices.details(), id],
  },
  gst: {
    all: ['gst'],
    config: () => [...queryKeys.gst.all, 'config'],
    rates: () => [...queryKeys.gst.all, 'rates'],
    hsn: {
      lookup: (code) => [...queryKeys.gst.all, 'hsn', code],
    },
  },
  warranty: {
    all: ['warranty'],
    lists: () => [...queryKeys.warranty.all, 'list'],
    list: (filters) => [...queryKeys.warranty.lists(), filters],
    details: () => [...queryKeys.warranty.all, 'detail'],
    detail: (id) => [...queryKeys.warranty.details(), id],
  },
  complaints: {
    all: ['complaints'],
    lists: () => [...queryKeys.complaints.all, 'list'],
    list: (filters) => [...queryKeys.complaints.lists(), filters],
    details: () => [...queryKeys.complaints.all, 'detail'],
    detail: (id) => [...queryKeys.complaints.details(), id],
    openCount: () => [...queryKeys.complaints.all, 'open-count'],
  },
  spares: {
    all: ['spares'],
    lists: () => [...queryKeys.spares.all, 'list'],
    list: (filters) => [...queryKeys.spares.lists(), filters],
    detail: (id) => [...queryKeys.spares.all, 'detail', id],
  },
  returns: {
    all: ['returns'],
    lists: () => [...queryKeys.returns.all, 'list'],
    list: (filters) => [...queryKeys.returns.lists(), filters],
    detail: (id) => [...queryKeys.returns.all, 'detail', id],
  },
  dealers: {
    all: ['dealers'],
    lists: () => [...queryKeys.dealers.all, 'list'],
    list: (filters) => [...queryKeys.dealers.lists(), filters],
    detail: (id) => [...queryKeys.dealers.all, 'detail', id],
  },
  employees: {
    all: ['employees'],
    lists: () => [...queryKeys.employees.all, 'list'],
    list: (filters) => [...queryKeys.employees.lists(), filters],
    detail: (id) => [...queryKeys.employees.all, 'detail', id],
    hierarchy: () => [...queryKeys.employees.all, 'hierarchy'],
  },
  employeeReportingLine: {
    all: ['employee-reporting-line'],
    detail: (id) => [...queryKeys.employeeReportingLine.all, 'detail', id],
  },
  employeeDealers: {
    all: ['employee-dealers'],
    detail: (id) => [...queryKeys.employeeDealers.all, 'detail', id],
  },
  assignedDealers: {
    all: ['assigned-dealers'],
    list: (filters) => [...queryKeys.assignedDealers.all, 'list', filters],
    team: (filters) => [...queryKeys.assignedDealers.all, 'team', filters],
    detail: (id) => [...queryKeys.assignedDealers.all, 'detail', id],
  },
  employeePerformance: {
    all: ['employee-performance'],
    get: (role) => [...queryKeys.employeePerformance.all, role],
    analytics: () => [...queryKeys.employeePerformance.all, 'analytics'],
  },
  tasks: {
    all: ['tasks'],
    lists: () => [...queryKeys.tasks.all, 'list'],
    list: (filters) => [...queryKeys.tasks.lists(), filters],
    detail: (id) => [...queryKeys.tasks.all, 'detail', id],
    pendingCount: () => [...queryKeys.tasks.all, 'pending-count'],
  },
  approvals: {
    all: ['approvals'],
    lists: () => [...queryKeys.approvals.all, 'list'],
    list: (filters) => [...queryKeys.approvals.lists(), filters],
    detail: (id) => [...queryKeys.approvals.all, 'detail', id],
    pendingCount: () => [...queryKeys.approvals.all, 'pending-count'],
  },
  orders: {
    all: ['orders'],
    lists: () => [...queryKeys.orders.all, 'list'],
    list: (filters) => [...queryKeys.orders.lists(), filters],
    detail: (id) => [...queryKeys.orders.all, 'detail', id],
  },
  serviceRequests: {
    all: ['service-requests'],
    lists: () => [...queryKeys.serviceRequests.all, 'list'],
    list: (filters) => [...queryKeys.serviceRequests.lists(), filters],
    detail: (id) => [...queryKeys.serviceRequests.all, 'detail', id],
  },
  analytics: {
    all: ['analytics'],
    dashboard: (panel, filters) => [...queryKeys.analytics.all, 'dashboard', panel, filters],
    revenue: (filters) => [...queryKeys.analytics.all, 'revenue', filters],
    complaints: (filters) => [...queryKeys.analytics.all, 'complaints', filters],
  },
  reports: {
    all: ['reports'],
    list: (filters) => ['reports', 'list', filters],
    detail: (id) => ['reports', 'detail', id],
  },
  notifications: {
    all: ['notifications'],
    list: (filters) => [...queryKeys.notifications.all, 'list', filters],
    infinite: (filters) => [...queryKeys.notifications.all, 'infinite', filters],
    unreadCount: () => [...queryKeys.notifications.all, 'unread-count'],
  },
  customerPortal: {
    all: ['customer-portal'],
    config: ['customer-portal', 'config'],
    hub: ['customer-portal', 'hub'],
    notifications: ['customer-portal', 'notifications'],
  },
  audit: {
    all: ['audit'],
    list: (filters) => [...queryKeys.audit.all, 'list', filters],
  },
  search: {
    all: ['search'],
    global: (query) => [...queryKeys.search.all, 'global', query],
  },
  address: {
    pincode: (pin) => ['address', 'pincode', pin],
    states: () => ['address', 'states'],
  },
};
