import {
  LayoutDashboard,
  Warehouse,
  Truck,
  Package,
  ArrowLeftRight,
  Users,
  UserCog,
  Settings,
  ScrollText,
  Receipt,
  FileText,
  Shield,
  ClipboardList,
  BarChart3,
  CheckSquare,
  Headphones,
  Wrench,
  RotateCcw,
  ShoppingBag,
  Boxes,
  Tags,
  Award,
  Layers,
  IndianRupee,
  Wallet,
  Bell,
  ClipboardCheck,
  Target,
  Globe,
  Contact,
  ShoppingCart,
  Factory,
  ArrowDownCircle,
  ArrowUpCircle,
  BookOpen,
  Undo2,
  Gift,
  ShieldCheck,
  Link2,
} from 'lucide-react';
import { PERMISSIONS } from '@/constants/permissions';
import { ROLES } from '@/constants/roles';
import { ROUTES } from '@/constants/routes';
import { env } from '@/config/env';

export const PANELS = {
  admin: {
    id: 'admin',
    label: 'Admin Console',
    roles: [ROLES.MASTER_ADMIN, ROLES.WAREHOUSE_MANAGER],
    baseRoute: '/admin',
    nav: [
      // Top Level Overview
      {
        id: 'dashboard',
        label: 'Dashboard',
        icon: LayoutDashboard,
        path: ROUTES.ADMIN_DASHBOARD,
        permission: PERMISSIONS.ANALYTICS_READ,
      },

      // 1. PRIMARY / PURCHASE & MANUFACTURING
      {
        id: 'items',
        label: 'Item Master',
        icon: Boxes,
        path: ROUTES.ADMIN_PRODUCTS,
        permission: PERMISSIONS.PRODUCTS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '1. PRIMARY / PURCHASE & MANUFACTURING',
      },
      {
        id: 'purchases',
        label: 'Purchase (Raw Material)',
        icon: ShoppingCart,
        path: ROUTES.ADMIN_PURCHASES,
        permission: PERMISSIONS.PURCHASES_READ,
        section: '1. PRIMARY / PURCHASE & MANUFACTURING',
      },
      {
        id: 'manufacture',
        label: 'Manufacture / Production',
        icon: Factory,
        path: ROUTES.ADMIN_MANUFACTURE,
        permission: PERMISSIONS.MANUFACTURE_READ,
        section: '1. PRIMARY / PURCHASE & MANUFACTURING',
      },
      {
        id: 'payment-out',
        label: 'Payment Out (Vendor Payment)',
        icon: ArrowUpCircle,
        path: ROUTES.ADMIN_PAYMENT_OUT,
        permission: PERMISSIONS.PURCHASES_READ,
        section: '1. PRIMARY / PURCHASE & MANUFACTURING',
      },
      {
        id: 'finished-goods',
        label: 'Finish Goods',
        icon: Package,
        path: ROUTES.ADMIN_FINISHED_GOODS,
        permission: PERMISSIONS.INVENTORY_READ,
        section: '1. PRIMARY / PURCHASE & MANUFACTURING',
      },

      // 2. SALES
      {
        id: 'sales-invoices',
        label: 'Sales Invoice',
        icon: FileText,
        path: ROUTES.ADMIN_SALES_INVOICES,
        permission: PERMISSIONS.PURCHASES_READ,
        section: '2. SALES',
      },
      {
        id: 'payment-in',
        label: 'Payment In',
        icon: ArrowDownCircle,
        path: ROUTES.ADMIN_PAYMENT_IN,
        permission: PERMISSIONS.PURCHASES_READ,
        section: '2. SALES',
      },
      {
        id: 'sale-po',
        label: 'Sales PO',
        icon: ShoppingBag,
        path: ROUTES.ADMIN_SALE_PO,
        permission: PERMISSIONS.PURCHASES_READ,
        section: '2. SALES',
      },
      {
        id: 'dealers',
        label: 'Dealer Management',
        icon: Users,
        path: ROUTES.ADMIN_DEALERS,
        permission: PERMISSIONS.DEALERS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '2. SALES',
      },
      {
        id: 'admin-dealer-sale-returns',
        label: 'Sales Return',
        icon: RotateCcw,
        path: ROUTES.ADMIN_DEALER_SALE_RETURNS,
        permission: PERMISSIONS.SALE_RETURNS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '2. SALES',
      },
      {
        id: 'inventory',
        label: 'Inventory Management',
        icon: Package,
        path: ROUTES.ADMIN_INVENTORY,
        permission: PERMISSIONS.INVENTORY_READ,
        badgeKey: 'inventory.lowStock',
        section: '2. SALES',
      },
      {
        id: 'admin-dealer-purchase-returns',
        label: 'Dealer Purchase Return / New Purchase Return',
        icon: Undo2,
        path: ROUTES.ADMIN_DEALER_PURCHASE_RETURNS,
        permission: PERMISSIONS.PURCHASE_RETURNS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '2. SALES',
      },

      // 3. ONBOARDING
      {
        id: 'parties',
        label: 'Party Master (Vendor / Dealer / Customer)',
        icon: Contact,
        path: ROUTES.ADMIN_PARTIES,
        permission: PERMISSIONS.PARTIES_READ,
        section: '3. ONBOARDING',
      },
      {
        id: 'brands',
        label: 'Brands Master',
        icon: Award,
        path: ROUTES.ADMIN_BRANDS,
        permission: PERMISSIONS.BRANDS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '3. ONBOARDING',
      },
      {
        id: 'categories',
        label: 'Category Master',
        icon: Tags,
        path: ROUTES.ADMIN_CATEGORIES,
        permission: PERMISSIONS.CATEGORIES_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '3. ONBOARDING',
      },
      {
        id: 'pricing',
        label: 'Pricing Master',
        icon: IndianRupee,
        path: ROUTES.ADMIN_PRICING,
        permission: PERMISSIONS.PRICING_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '3. ONBOARDING',
      },
      {
        id: 'tiers',
        label: 'Product Tiers',
        icon: Layers,
        path: ROUTES.ADMIN_PRODUCT_TIERS,
        permission: PERMISSIONS.PRICING_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '3. ONBOARDING',
      },

      // 4. DISPATCH & WAREHOUSE
      {
        id: 'grn',
        label: 'GRN (Goods Receipt Note)',
        icon: ClipboardCheck,
        path: ROUTES.ADMIN_GRN,
        permission: PERMISSIONS.GRN_READ,
        badgeKey: 'grn.pending',
        section: '4. DISPATCH & WAREHOUSE',
      },
      {
        id: 'warehouses',
        label: 'Warehouse Management',
        icon: Warehouse,
        path: ROUTES.ADMIN_WAREHOUSES,
        permission: PERMISSIONS.WAREHOUSES_READ,
        section: '4. DISPATCH & WAREHOUSE',
      },
      {
        id: 'stock-movements',
        label: 'Stock Movement / Transfer',
        icon: ArrowLeftRight,
        path: ROUTES.ADMIN_STOCK_MOVEMENTS,
        permission: PERMISSIONS.INVENTORY_READ,
        section: '4. DISPATCH & WAREHOUSE',
      },
      {
        id: 'grn-monitoring',
        label: 'GRN Monitoring / Tracking',
        icon: ClipboardList,
        path: ROUTES.ADMIN_GRN,
        permission: PERMISSIONS.GRN_READ,
        section: '4. DISPATCH & WAREHOUSE',
      },
      {
        id: 'dispatch',
        label: 'Dispatch Management',
        icon: Truck,
        path: ROUTES.ADMIN_DISPATCH,
        permission: PERMISSIONS.DISPATCH_READ,
        badgeKey: 'dispatch.pending',
        section: '4. DISPATCH & WAREHOUSE',
      },

      // 5. CUSTOMER & DEALER BILLING
      {
        id: 'customer-invoices',
        label: 'Customer Invoice',
        icon: Receipt,
        path: '/admin/dealer-invoices',
        permission: PERMISSIONS.DEALERS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '5. CUSTOMER & DEALER BILLING',
      },
      {
        id: 'dealer-invoices',
        label: 'Dealer Invoice',
        icon: FileText,
        path: ROUTES.ADMIN_SALES_INVOICES,
        permission: PERMISSIONS.PURCHASES_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '5. CUSTOMER & DEALER BILLING',
      },
      {
        id: 'referral-linking',
        label: 'Referral Linking in Invoice',
        icon: Link2,
        path: ROUTES.ADMIN_REFERRALS,
        permission: PERMISSIONS.ANALYTICS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '5. CUSTOMER & DEALER BILLING',
      },

      // 6. REFERRAL SYSTEM
      {
        id: 'referrals',
        label: 'Referral Master',
        icon: Gift,
        path: ROUTES.ADMIN_REFERRALS,
        permission: PERMISSIONS.ANALYTICS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '6. REFERRAL SYSTEM',
      },
      {
        id: 'referral-payouts',
        label: 'Referral Commission / Payout',
        icon: Wallet,
        path: '/admin/referrals?tab=withdrawals',
        permission: PERMISSIONS.ANALYTICS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '6. REFERRAL SYSTEM',
      },

      // 7. INSURANCE & WARRANTY
      {
        id: 'admin-insurance',
        label: 'Insurance Management',
        icon: Shield,
        path: ROUTES.ADMIN_INSURANCE,
        permission: PERMISSIONS.INSURANCE_CLAIMS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '7. INSURANCE & WARRANTY',
      },
      {
        id: 'admin-warranty',
        label: 'Extended Warranty Management',
        icon: ShieldCheck,
        path: '/admin/warranty',
        permission: PERMISSIONS.WARRANTY_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '7. INSURANCE & WARRANTY',
      },

      // 8. SERVICE CENTRE
      {
        id: 'admin-complaints',
        label: 'Complaint / Ticket Management',
        icon: Headphones,
        path: ROUTES.ADMIN_COMPLAINTS,
        permission: PERMISSIONS.COMPLAINTS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '8. SERVICE CENTRE',
      },
      {
        id: 'admin-job-cards',
        label: 'Job Card Creation & Tracking',
        icon: ScrollText,
        path: ROUTES.ADMIN_JOB_CARDS,
        permission: PERMISSIONS.COMPLAINTS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '8. SERVICE CENTRE',
      },
      {
        id: 'service-centers',
        label: 'Service Management',
        icon: Wrench,
        path: ROUTES.ADMIN_SERVICE_CENTERS,
        permission: PERMISSIONS.COMPLAINTS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '8. SERVICE CENTRE',
      },

      // 9. SYSTEM & REPORTS
      {
        id: 'employees',
        label: 'Employees',
        icon: UserCog,
        path: ROUTES.ADMIN_EMPLOYEES,
        permission: PERMISSIONS.EMPLOYEES_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '9. SYSTEM & REPORTS',
      },
      {
        id: 'approvals',
        label: 'Approvals',
        icon: ClipboardList,
        path: ROUTES.ADMIN_APPROVALS,
        permission: PERMISSIONS.APPROVALS_READ,
        roles: [ROLES.MASTER_ADMIN],
        badgeKey: 'approvals.pending',
        section: '9. SYSTEM & REPORTS',
      },
      {
        id: 'expenses',
        label: 'Expenses',
        icon: Wallet,
        path: ROUTES.ADMIN_EXPENSES,
        permission: PERMISSIONS.EXPENSES_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '9. SYSTEM & REPORTS',
      },
      {
        id: 'reports',
        label: 'Reports & Analytics',
        icon: BarChart3,
        path: ROUTES.ADMIN_REPORTS,
        permission: PERMISSIONS.REPORTS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '9. SYSTEM & REPORTS',
      },
      {
        id: 'ledger',
        label: 'Party Ledger',
        icon: BookOpen,
        path: ROUTES.ADMIN_LEDGER,
        permission: PERMISSIONS.REPORTS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '9. SYSTEM & REPORTS',
      },
      {
        id: 'company-ledger',
        label: 'Company Ledger',
        icon: IndianRupee,
        path: ROUTES.ADMIN_COMPANY_LEDGER,
        permission: PERMISSIONS.REPORTS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '9. SYSTEM & REPORTS',
      },
      {
        id: 'notifications',
        label: 'Notifications',
        icon: Bell,
        path: ROUTES.ADMIN_NOTIFICATIONS,
        permission: PERMISSIONS.NOTIFICATIONS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '9. SYSTEM & REPORTS',
      },
      {
        id: 'settings',
        label: 'Settings',
        icon: Settings,
        path: ROUTES.ADMIN_SETTINGS,
        permission: PERMISSIONS.SETTINGS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '9. SYSTEM & REPORTS',
      },
      {
        id: 'audit',
        label: 'Audit Logs',
        icon: ScrollText,
        path: ROUTES.ADMIN_AUDIT_LOGS,
        permission: PERMISSIONS.AUDIT_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '9. SYSTEM & REPORTS',
      },
      {
        id: 'cms',
        label: 'Website CMS',
        icon: Globe,
        path: ROUTES.ADMIN_CMS,
        permission: PERMISSIONS.CMS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '9. SYSTEM & REPORTS',
      },
      {
        id: 'store-orders',
        label: 'Website Orders',
        icon: ShoppingBag,
        path: ROUTES.ADMIN_STORE_ORDERS,
        permission: PERMISSIONS.STORE_ORDERS_READ,
        roles: [ROLES.MASTER_ADMIN],
        section: '9. SYSTEM & REPORTS',
      },
    ],
  },
  dealer: {
    id: 'dealer',
    label: 'Dealer Workspace',
    roles: [ROLES.DEALER_ADMIN, ROLES.DEALER_SALES],
    baseRoute: '/dealer',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: ROUTES.DEALER_DASHBOARD, permission: PERMISSIONS.DEALER_DASHBOARD, roles: [ROLES.DEALER_ADMIN] },
      { id: 'quick-sale', label: 'Quick Sale', icon: Receipt, path: ROUTES.DEALER_SALES_QUICK, permission: PERMISSIONS.BILLING_CREATE },
      { id: 'dispatches', label: 'Dispatches', icon: Truck, path: ROUTES.DEALER_DISPATCHES, permission: PERMISSIONS.DEALER_DISPATCH_READ, badgeKey: 'dispatch.pending' },
      { id: 'grn', label: 'GRN', icon: ClipboardCheck, path: ROUTES.DEALER_GRN, permission: PERMISSIONS.DEALER_GRN_READ, badgeKey: 'grn.pending' },
      { id: 'orders', label: 'Orders', icon: ClipboardList, path: ROUTES.DEALER_ORDERS, permission: PERMISSIONS.DEALER_DASHBOARD },
      { id: 'inventory', label: 'Inventory', icon: Package, path: ROUTES.DEALER_INVENTORY, permission: PERMISSIONS.DEALER_INVENTORY_READ },
      { id: 'customers', label: 'Customers', icon: Users, path: ROUTES.DEALER_CUSTOMERS, permission: PERMISSIONS.DEALER_CUSTOMERS_READ },
      { id: 'billing', label: 'Billing', icon: Receipt, path: ROUTES.DEALER_BILLING, permission: PERMISSIONS.BILLING_READ },
      { id: 'invoices', label: 'Invoices', icon: FileText, path: ROUTES.DEALER_INVOICES, permission: PERMISSIONS.INVOICES_READ },
      { id: 'warranty', label: 'Warranty', icon: Shield, path: ROUTES.DEALER_WARRANTY, permission: PERMISSIONS.WARRANTY_READ },
      { id: 'insurance', label: 'Insurance', icon: Shield, path: ROUTES.DEALER_INSURANCE, permission: PERMISSIONS.INSURANCE_CLAIMS_READ },
      { id: 'sale-returns', label: 'Sale Returns', icon: RotateCcw, path: ROUTES.DEALER_SALE_RETURNS, permission: PERMISSIONS.SALE_RETURNS_READ },
      { id: 'purchase-returns', label: 'Purchase Returns', icon: Undo2, path: ROUTES.DEALER_PURCHASE_RETURNS, permission: PERMISSIONS.PURCHASE_RETURNS_READ },
      { id: 'reports', label: 'Reports', icon: BarChart3, path: ROUTES.DEALER_REPORTS, permission: PERMISSIONS.DEALER_REPORTS_READ },
      { id: 'team', label: 'Team', icon: UserCog, path: ROUTES.DEALER_TEAM, permission: PERMISSIONS.DEALER_TEAM_READ, roles: [ROLES.DEALER_ADMIN] },
    ],
  },
  employee: {
    id: 'employee',
    label: 'Employee Hub',
    roles: [ROLES.EMPLOYEE, ROLES.MANAGER],
    baseRoute: '/employee',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: ROUTES.EMPLOYEE_DASHBOARD },
      { id: 'dealers', label: 'Assigned Dealers', icon: Users, path: ROUTES.EMPLOYEE_DEALERS, permission: PERMISSIONS.EMPLOYEE_DEALERS_READ },
      { id: 'analytics', label: 'Dealer Analytics', icon: BarChart3, path: ROUTES.EMPLOYEE_DEALER_ANALYTICS, permission: PERMISSIONS.EMPLOYEE_ANALYTICS_READ },
      { id: 'performance', label: 'Performance', icon: Target, path: ROUTES.EMPLOYEE_PERFORMANCE, permission: PERMISSIONS.EMPLOYEE_PERFORMANCE_READ },
      { id: 'tasks', label: 'Tasks', icon: CheckSquare, path: ROUTES.EMPLOYEE_TASKS, permission: PERMISSIONS.TASKS_READ, badgeKey: 'tasks.pending' },
      { id: 'reports', label: 'Reports', icon: FileText, path: ROUTES.EMPLOYEE_REPORTS, permission: PERMISSIONS.REPORTS_READ },
      { id: 'team', label: 'Team', icon: UserCog, path: ROUTES.EMPLOYEE_TEAM, permission: PERMISSIONS.TEAM_READ, roles: [ROLES.MANAGER] },
      { id: 'approvals', label: 'Approvals', icon: ClipboardList, path: ROUTES.EMPLOYEE_APPROVALS, permission: PERMISSIONS.APPROVALS_READ, roles: [ROLES.MANAGER], badgeKey: 'approvals.pending' },
    ],
  },
  service: {
    id: 'service',
    label: 'Service Console',
    roles: [ROLES.CUSTOMER_SUPPORT, ROLES.SERVICE_CENTER],
    baseRoute: '/service',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: ROUTES.SERVICE_DASHBOARD, permission: PERMISSIONS.SERVICE_DASHBOARD },
      { id: 'walkin', label: 'Walk-in Service', icon: ClipboardList, path: ROUTES.SERVICE_WALKIN, roles: [ROLES.SERVICE_CENTER, ROLES.CUSTOMER_SUPPORT] },
      { id: 'job-cards', label: 'Job Cards', icon: ScrollText, path: ROUTES.SERVICE_JOB_CARDS, roles: [ROLES.SERVICE_CENTER, ROLES.CUSTOMER_SUPPORT] },
      { id: 'inventory', label: 'Service Inventory', icon: Boxes, path: ROUTES.SERVICE_INVENTORY, roles: [ROLES.SERVICE_CENTER] },
      { id: 'tickets', label: 'Service Tickets', icon: Headphones, path: ROUTES.SERVICE_TICKETS, permission: PERMISSIONS.SERVICE_REQUESTS_READ },
      { id: 'complaints', label: 'Complaints', icon: Headphones, path: ROUTES.SERVICE_COMPLAINTS, permission: PERMISSIONS.COMPLAINTS_READ, badgeKey: 'complaints.open', roles: [ROLES.CUSTOMER_SUPPORT] },
      { id: 'spares', label: 'Spare Parts', icon: Wrench, path: ROUTES.SERVICE_SPARE_PARTS, permission: PERMISSIONS.SPARES_READ, roles: [ROLES.SERVICE_CENTER] },
      { id: 'returns', label: 'Defective Returns', icon: RotateCcw, path: ROUTES.SERVICE_DEFECTIVE_RETURNS, permission: PERMISSIONS.RETURNS_READ, roles: [ROLES.SERVICE_CENTER] },
    ],
  },
  customer: {
    id: 'customer',
    label: 'Customer Portal',
    roles: [ROLES.CUSTOMER],
    baseRoute: '/customer',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: ROUTES.CUSTOMER_DASHBOARD },
      { id: 'referral', label: 'Refer & Earn ₹40k', icon: Gift, path: '/customer/referral' },
      { id: 'products', label: 'My Products', icon: Package, path: ROUTES.CUSTOMER_PRODUCTS },
      { id: 'warranty', label: 'Warranty', icon: Shield, path: ROUTES.CUSTOMER_WARRANTY, permission: PERMISSIONS.WARRANTY_READ },
      { id: 'complaints', label: 'Raise Complaint', icon: Headphones, path: '/customer/complaints' },
      { id: 'service', label: 'Service Requests', icon: Headphones, path: ROUTES.CUSTOMER_SERVICE_REQUESTS, permission: PERMISSIONS.SERVICE_REQUESTS_READ },
      { id: 'orders', label: 'Orders', icon: ShoppingBag, path: ROUTES.CUSTOMER_ORDERS, permission: PERMISSIONS.ORDERS_READ },
    ],
  },
};

export function getPanelForRole(role) {
  return Object.values(PANELS).find((p) => p.roles.includes(role)) || null;
}

export function getNavForPanel(panelId, role, hasPermission) {
  const panel = PANELS[panelId];
  if (!panel) return [];

  const bypass = role === ROLES.MASTER_ADMIN || (env.useMockApi && env.isDev);

  return panel.nav.filter((item) => {
    if (!bypass) {
      if (item.roles && !item.roles.includes(role)) return false;
      if (item.permission && !hasPermission(item.permission)) return false;
    }
    return true;
  });
}
