/** Professional invoice theme design tokens */

export const THEME_CATEGORIES = {
  PROFESSIONAL: 'Professional',
  FESTIVAL: 'Festival Collection',
};

export const INVOICE_THEMES = [
  {
    id: 'luxury',
    label: 'Luxury Gold',
    category: THEME_CATEGORIES.PROFESSIONAL,
    description: 'Navy & gold premium frame — ideal for GST tax invoices',
    accent: '#b8860b',
    accentSecondary: '#1e3a5f',
    accentLight: '#faf6ee',
    border: '#c9a227',
    borderInner: '#e8d5a3',
    headerBg: 'linear-gradient(180deg, #faf8f3 0%, #ffffff 100%)',
    headerText: '#1e3a5f',
    tableHead: '#ece7dc',
    tableHeadText: '#1e293b',
    ribbonBg: null,
    ribbonText: null,
    motif: null,
    fontDisplay: '"Playfair Display", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    darkHeader: false,
  },
  {
    id: 'stylish',
    label: 'Haion Signature',
    category: THEME_CATEGORIES.PROFESSIONAL,
    description: 'Haion brand copper tones with refined typography',
    accent: '#a85a3c',
    accentSecondary: '#5c2e1f',
    accentLight: '#fdf6f2',
    border: '#c4714f',
    borderInner: '#e8c4b4',
    headerBg: 'linear-gradient(135deg, #fdf6f2 0%, #ffffff 55%)',
    headerText: '#5c2e1f',
    tableHead: '#f5e6dc',
    tableHeadText: '#3d2318',
    ribbonBg: null,
    ribbonText: null,
    motif: null,
    fontDisplay: '"Cormorant Garamond", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    darkHeader: false,
  },
  {
    id: 'advanced-gst',
    label: 'GST Classic',
    category: THEME_CATEGORIES.PROFESSIONAL,
    description: 'Clean Tally-style layout for accountants & CA reports',
    accent: '#334155',
    accentSecondary: '#0f172a',
    accentLight: '#f8fafc',
    border: '#64748b',
    borderInner: '#cbd5e1',
    headerBg: '#f8fafc',
    headerText: '#0f172a',
    tableHead: '#e2e8f0',
    tableHeadText: '#334155',
    ribbonBg: null,
    ribbonText: null,
    motif: null,
    fontDisplay: '"DM Sans", "Inter", sans-serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    darkHeader: false,
  },
  {
    id: 'executive',
    label: 'Executive Black',
    category: THEME_CATEGORIES.PROFESSIONAL,
    description: 'High-contrast charcoal with platinum accents',
    accent: '#a8a29e',
    accentSecondary: '#1c1917',
    accentLight: '#f5f5f4',
    border: '#78716c',
    borderInner: '#d6d3d1',
    headerBg: 'linear-gradient(180deg, #1c1917 0%, #292524 100%)',
    headerText: '#fafaf9',
    tableHead: '#e7e5e4',
    tableHeadText: '#1c1917',
    ribbonBg: null,
    ribbonText: null,
    motif: null,
    fontDisplay: '"Playfair Display", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    darkHeader: true,
  },
  {
    id: 'corporate',
    label: 'Corporate Blue',
    category: THEME_CATEGORIES.PROFESSIONAL,
    description: 'Trusted corporate blue for dealers & distributors',
    accent: '#1d4ed8',
    accentSecondary: '#1e3a8a',
    accentLight: '#eff6ff',
    border: '#3b82f6',
    borderInner: '#93c5fd',
    headerBg: 'linear-gradient(180deg, #eff6ff 0%, #ffffff 100%)',
    headerText: '#1e3a8a',
    tableHead: '#dbeafe',
    tableHeadText: '#1e40af',
    ribbonBg: null,
    ribbonText: null,
    motif: null,
    fontDisplay: '"Playfair Display", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    darkHeader: false,
  },
  // Festival — subtle motifs & elegant ribbon text, no emoji
  {
    id: 'makar-sankranti',
    label: 'Makar Sankranti',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'January — warm harvest tones',
    accent: '#c2410c',
    accentSecondary: '#7c2d12',
    accentLight: '#fff7ed',
    border: '#ea580c',
    borderInner: '#fdba74',
    headerBg: 'linear-gradient(180deg, #fff7ed 0%, #ffffff 100%)',
    headerText: '#7c2d12',
    tableHead: '#ffedd5',
    tableHeadText: '#9a3412',
    ribbonBg: 'linear-gradient(90deg, #7c2d12, #c2410c, #7c2d12)',
    ribbonText: 'Wishing you a prosperous harvest season',
    motif: 'kite',
    fontDisplay: '"Cormorant Garamond", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [1],
    darkHeader: false,
  },
  {
    id: 'maha-shivratri',
    label: 'Maha Shivratri',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'February — deep indigo devotion',
    accent: '#7c3aed',
    accentSecondary: '#312e81',
    accentLight: '#f5f3ff',
    border: '#8b5cf6',
    borderInner: '#c4b5fd',
    headerBg: 'linear-gradient(180deg, #312e81 0%, #1e1b4b 100%)',
    headerText: '#ede9fe',
    tableHead: '#ede9fe',
    tableHeadText: '#312e81',
    ribbonBg: 'linear-gradient(90deg, #1e1b4b, #5b21b6, #1e1b4b)',
    ribbonText: 'Om Namah Shivaya',
    motif: 'trident',
    fontDisplay: '"Cormorant Garamond", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [2],
    darkHeader: true,
  },
  {
    id: 'holi',
    label: 'Holi',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'March — refined festive palette',
    accent: '#be185d',
    accentSecondary: '#831843',
    accentLight: '#fdf2f8',
    border: '#db2777',
    borderInner: '#f9a8d4',
    headerBg: 'linear-gradient(135deg, #fdf2f8 0%, #faf5ff 50%, #eff6ff 100%)',
    headerText: '#831843',
    tableHead: '#fce7f3',
    tableHeadText: '#9d174d',
    ribbonBg: 'linear-gradient(90deg, #831843, #a21caf, #1d4ed8, #831843)',
    ribbonText: 'Celebrating the festival of colours',
    motif: 'rangoli',
    fontDisplay: '"Playfair Display", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [3],
    darkHeader: false,
  },
  {
    id: 'ugadi',
    label: 'Ugadi / Gudi Padwa',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'March–April — new year elegance',
    accent: '#15803d',
    accentSecondary: '#14532d',
    accentLight: '#f0fdf4',
    border: '#16a34a',
    borderInner: '#86efac',
    headerBg: 'linear-gradient(180deg, #f0fdf4 0%, #fefce8 100%)',
    headerText: '#14532d',
    tableHead: '#dcfce7',
    tableHeadText: '#166534',
    ribbonBg: 'linear-gradient(90deg, #14532d, #15803d, #14532d)',
    ribbonText: 'Happy New Year — Ugadi Gudi Padwa',
    motif: 'floral',
    fontDisplay: '"Cormorant Garamond", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [3, 4],
    darkHeader: false,
  },
  {
    id: 'ram-navami',
    label: 'Ram Navami',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'April — serene royal blue',
    accent: '#1d4ed8',
    accentSecondary: '#1e3a8a',
    accentLight: '#eff6ff',
    border: '#2563eb',
    borderInner: '#93c5fd',
    headerBg: 'linear-gradient(180deg, #eff6ff 0%, #fffbeb 100%)',
    headerText: '#1e3a8a',
    tableHead: '#dbeafe',
    tableHeadText: '#1e40af',
    ribbonBg: 'linear-gradient(90deg, #1e3a8a, #2563eb, #1e3a8a)',
    ribbonText: 'Jai Shri Ram',
    motif: 'floral',
    fontDisplay: '"Cormorant Garamond", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [4],
    darkHeader: false,
  },
  {
    id: 'akshaya-tritiya',
    label: 'Akshaya Tritiya',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'May — golden auspicious tones',
    accent: '#a16207',
    accentSecondary: '#713f12',
    accentLight: '#fefce8',
    border: '#ca8a04',
    borderInner: '#fde047',
    headerBg: 'linear-gradient(180deg, #fefce8 0%, #ffffff 100%)',
    headerText: '#713f12',
    tableHead: '#fef9c3',
    tableHeadText: '#854d0e',
    ribbonBg: 'linear-gradient(90deg, #713f12, #a16207, #713f12)',
    ribbonText: 'Wishing you eternal prosperity',
    motif: 'sparkle',
    fontDisplay: '"Playfair Display", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [5],
    darkHeader: false,
  },
  {
    id: 'guru-purnima',
    label: 'Guru Purnima',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'July — tranquil teal gratitude',
    accent: '#0f766e',
    accentSecondary: '#134e4a',
    accentLight: '#f0fdfa',
    border: '#0d9488',
    borderInner: '#5eead4',
    headerBg: 'linear-gradient(180deg, #f0fdfa 0%, #ffffff 100%)',
    headerText: '#134e4a',
    tableHead: '#ccfbf1',
    tableHeadText: '#115e59',
    ribbonBg: 'linear-gradient(90deg, #134e4a, #0f766e, #134e4a)',
    ribbonText: 'Honouring our teachers and gurus',
    motif: 'om',
    fontDisplay: '"Cormorant Garamond", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [7],
    darkHeader: false,
  },
  {
    id: 'raksha-bandhan',
    label: 'Raksha Bandhan',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'August — rose gold sibling bond',
    accent: '#be123c',
    accentSecondary: '#881337',
    accentLight: '#fff1f2',
    border: '#e11d48',
    borderInner: '#fda4af',
    headerBg: 'linear-gradient(180deg, #fff1f2 0%, #fdf2f8 100%)',
    headerText: '#881337',
    tableHead: '#ffe4e6',
    tableHeadText: '#9f1239',
    ribbonBg: 'linear-gradient(90deg, #881337, #be123c, #881337)',
    ribbonText: 'Celebrating the bond of protection',
    motif: 'bow',
    fontDisplay: '"Playfair Display", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [8],
    darkHeader: false,
  },
  {
    id: 'janmashtami',
    label: 'Janmashtami',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'August — royal peacock blue',
    accent: '#4338ca',
    accentSecondary: '#312e81',
    accentLight: '#eef2ff',
    border: '#4f46e5',
    borderInner: '#a5b4fc',
    headerBg: 'linear-gradient(180deg, #eef2ff 0%, #e0e7ff 100%)',
    headerText: '#312e81',
    tableHead: '#e0e7ff',
    tableHeadText: '#3730a3',
    ribbonBg: 'linear-gradient(90deg, #312e81, #4338ca, #312e81)',
    ribbonText: 'Celebrating Krishna Janmashtami',
    motif: 'floral',
    fontDisplay: '"Cormorant Garamond", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [8],
    darkHeader: false,
  },
  {
    id: 'ganesh-chaturthi',
    label: 'Ganesh Chaturthi',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'August–September — auspicious saffron',
    accent: '#b45309',
    accentSecondary: '#78350f',
    accentLight: '#fffbeb',
    border: '#d97706',
    borderInner: '#fcd34d',
    headerBg: 'linear-gradient(180deg, #fffbeb 0%, #fef3c7 100%)',
    headerText: '#78350f',
    tableHead: '#fde68a',
    tableHeadText: '#92400e',
    ribbonBg: 'linear-gradient(90deg, #78350f, #b45309, #78350f)',
    ribbonText: 'Ganpati Bappa Morya',
    motif: 'lotus',
    fontDisplay: '"Cormorant Garamond", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [8, 9],
    darkHeader: false,
  },
  {
    id: 'navratri',
    label: 'Navratri',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'September–October — regal magenta',
    accent: '#a21caf',
    accentSecondary: '#701a75',
    accentLight: '#fdf4ff',
    border: '#c026d3',
    borderInner: '#e879f9',
    headerBg: 'linear-gradient(135deg, #fdf4ff 0%, #fff7ed 100%)',
    headerText: '#701a75',
    tableHead: '#fae8ff',
    tableHeadText: '#86198f',
    ribbonBg: 'linear-gradient(90deg, #701a75, #a21caf, #701a75)',
    ribbonText: 'Nine nights of devotion and celebration',
    motif: 'garland',
    fontDisplay: '"Playfair Display", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [9, 10],
    darkHeader: false,
  },
  {
    id: 'dussehra',
    label: 'Dussehra',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'October — victory crimson',
    accent: '#b91c1c',
    accentSecondary: '#7f1d1d',
    accentLight: '#fef2f2',
    border: '#dc2626',
    borderInner: '#fca5a5',
    headerBg: 'linear-gradient(180deg, #fef2f2 0%, #fff7ed 100%)',
    headerText: '#7f1d1d',
    tableHead: '#fee2e2',
    tableHeadText: '#991b1b',
    ribbonBg: 'linear-gradient(90deg, #7f1d1d, #b91c1c, #7f1d1d)',
    ribbonText: 'Victory of good over evil',
    motif: 'floral',
    fontDisplay: '"Cormorant Garamond", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [10],
    darkHeader: false,
  },
  {
    id: 'diwali',
    label: 'Diwali',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'October–November — luxury deep navy & gold',
    accent: '#d97706',
    accentSecondary: '#fef3c7',
    accentLight: '#fffbeb',
    border: '#f59e0b',
    borderInner: '#fcd34d',
    headerBg: 'linear-gradient(180deg, #1e1b4b 0%, #312e81 50%, #451a03 100%)',
    headerText: '#fef3c7',
    tableHead: '#fde68a',
    tableHeadText: '#451a03',
    ribbonBg: 'linear-gradient(90deg, #451a03, #b45309, #451a03)',
    ribbonText: 'Shubh Deepavali — Festival of Lights',
    motif: 'diya',
    fontDisplay: '"Playfair Display", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [10, 11],
    darkHeader: true,
  },
  {
    id: 'bhai-dooj',
    label: 'Bhai Dooj',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'November — elegant rose',
    accent: '#be185d',
    accentSecondary: '#831843',
    accentLight: '#fdf2f8',
    border: '#db2777',
    borderInner: '#f9a8d4',
    headerBg: 'linear-gradient(180deg, #fdf2f8 0%, #ffffff 100%)',
    headerText: '#831843',
    tableHead: '#fce7f3',
    tableHeadText: '#9d174d',
    ribbonBg: 'linear-gradient(90deg, #831843, #be185d, #831843)',
    ribbonText: 'Celebrating the sibling bond',
    motif: 'bow',
    fontDisplay: '"Playfair Display", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [11],
    darkHeader: false,
  },
  {
    id: 'new-year',
    label: 'New Year',
    category: THEME_CATEGORIES.FESTIVAL,
    description: 'December — midnight blue celebration',
    accent: '#0284c7',
    accentSecondary: '#e0f2fe',
    accentLight: '#f0f9ff',
    border: '#0ea5e9',
    borderInner: '#7dd3fc',
    headerBg: 'linear-gradient(180deg, #0c4a6e 0%, #0369a1 100%)',
    headerText: '#e0f2fe',
    tableHead: '#bae6fd',
    tableHeadText: '#0c4a6e',
    ribbonBg: 'linear-gradient(90deg, #0c4a6e, #0284c7, #0c4a6e)',
    ribbonText: 'Wishing you a prosperous New Year',
    motif: 'sparkle',
    fontDisplay: '"Playfair Display", Georgia, serif',
    fontBody: '"DM Sans", "Inter", sans-serif',
    activeMonths: [12],
    darkHeader: true,
  },
];

export function getInvoiceTheme(id) {
  return INVOICE_THEMES.find((t) => t.id === id) || INVOICE_THEMES[0];
}

export function resolveEffectiveInvoiceTheme(inv = {}, date = new Date()) {
  if (inv.autoFestivalTheme) {
    const suggested = getSuggestedFestivalThemes(date);
    if (suggested.length > 0) return getInvoiceTheme(suggested[0].id);
  }
  return getInvoiceTheme(inv.theme || 'luxury');
}

export function getSuggestedFestivalThemes(date = new Date()) {
  const month = date.getMonth() + 1;
  return INVOICE_THEMES.filter(
    (t) => t.category === THEME_CATEGORIES.FESTIVAL && t.activeMonths?.includes(month)
  );
}

export function amountInWords(num) {
  const n = Math.round(num);
  if (n === 0) return 'Zero Rupees Only';
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten',
    'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  const two = (x) => {
    if (x < 20) return ones[x];
    return `${tens[Math.floor(x / 10)]}${ones[x % 10] ? ` ${ones[x % 10]}` : ''}`;
  };
  const three = (x) => {
    if (x < 100) return two(x);
    return `${ones[Math.floor(x / 100)]} Hundred${x % 100 ? ` ${two(x % 100)}` : ''}`;
  };
  let rem = n;
  let words = '';
  if (rem >= 10000000) { words += `${three(Math.floor(rem / 10000000))} Crore `; rem %= 10000000; }
  if (rem >= 100000) { words += `${three(Math.floor(rem / 100000))} Lakh `; rem %= 100000; }
  if (rem >= 1000) { words += `${three(Math.floor(rem / 1000))} Thousand `; rem %= 1000; }
  if (rem > 0) words += three(rem);
  return `${words.trim()} Rupees Only`;
}
