export const ROUTES = {
  ROOT: '/',

  // Auth
  AUTH_LOGIN: '/auth/login',
  AUTH_FORGOT_PASSWORD: '/auth/forgot-password',
  AUTH_RESET_PASSWORD: '/auth/reset-password',
  AUTH_SESSION_EXPIRED: '/auth/session-expired',

  // Admin
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCT_DETAIL: '/admin/products/:id',
  ADMIN_PARTIES: '/admin/parties',
  ADMIN_PARTY_NEW: '/admin/parties/new',
  ADMIN_PARTY_EDIT: '/admin/parties/:id/edit',
  ADMIN_PARTY_DETAIL: '/admin/parties/:id',
  ADMIN_PURCHASES: '/admin/purchases',
  ADMIN_PURCHASE_NEW: '/admin/purchases/new',
  ADMIN_PURCHASE_DETAIL: '/admin/purchases/:id',
  ADMIN_MANUFACTURE: '/admin/manufacture',
  ADMIN_MANUFACTURE_NEW: '/admin/manufacture/new',
  ADMIN_MANUFACTURE_DETAIL: '/admin/manufacture/:id',
  ADMIN_FINISHED_GOODS: '/admin/finished-goods',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_CATEGORY_DETAIL: '/admin/categories/:id',
  ADMIN_BRANDS: '/admin/brands',
  ADMIN_BRAND_DETAIL: '/admin/brands/:id',
  ADMIN_PRODUCT_TIERS: '/admin/product-tiers',
  ADMIN_PRICING: '/admin/pricing',
  ADMIN_PRICING_DETAIL: '/admin/pricing/:id',
  ADMIN_GRN: '/admin/grn',
  ADMIN_GRN_DETAIL: '/admin/grn/:id',
  ADMIN_EXPENSES: '/admin/expenses',
  ADMIN_EXPENSE_DETAIL: '/admin/expenses/:id',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_NOTIFICATIONS: '/admin/notifications',
  ADMIN_WAREHOUSES: '/admin/warehouses',
  ADMIN_WAREHOUSE_DETAIL: '/admin/warehouses/:id',
  ADMIN_WAREHOUSE_GRN: '/admin/warehouses/:id/grn',
  ADMIN_DISPATCH: '/admin/dispatch',
  ADMIN_DISPATCH_DETAIL: '/admin/dispatch/:id',
  ADMIN_INVENTORY: '/admin/inventory',
  ADMIN_INVENTORY_DETAIL: '/admin/inventory/:id',
  ADMIN_STOCK_MOVEMENTS: '/admin/stock-movements',
  ADMIN_DEALERS: '/admin/dealers',
  ADMIN_DEALER_DETAIL: '/admin/dealers/:id',
  ADMIN_DEALER_ONBOARDING: '/admin/dealers/onboarding',
  ADMIN_EMPLOYEES: '/admin/employees',
  ADMIN_EMPLOYEE_DETAIL: '/admin/employees/:id',
  ADMIN_APPROVALS: '/admin/approvals',
  ADMIN_APPROVAL_DETAIL: '/admin/approvals/:id',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_SETTINGS_GENERAL: '/admin/settings/general',
  ADMIN_SETTINGS_GST: '/admin/settings/gst',
  ADMIN_SETTINGS_NOTIFICATIONS: '/admin/settings/notifications',
  ADMIN_SETTINGS_CUSTOMER_PORTAL: '/admin/settings/customer-portal',
  ADMIN_SETTINGS_CA_REPORTS: '/admin/settings/ca-reports',
  ADMIN_BUSINESS_MANAGE: '/admin/business/manage',
  ADMIN_BUSINESS_INVOICE: '/admin/business/invoice',
  ADMIN_BUSINESS_PRINT: '/admin/business/print',
  ADMIN_SETTINGS_ROLES: '/admin/settings/roles',
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',

  // Website CMS
  ADMIN_CMS: '/admin/cms',
  ADMIN_CMS_SETTINGS: '/admin/cms/settings',
  ADMIN_CMS_PAGES_HOME: '/admin/cms/pages/home',
  ADMIN_CMS_PAGES_STORE: '/admin/cms/pages/store',
  ADMIN_CMS_PAGES_ABOUT: '/admin/cms/pages/about',
  ADMIN_CMS_PAGES_APPLIANCES: '/admin/cms/pages/appliances',
  ADMIN_CMS_PAGES_INVERTER: '/admin/cms/pages/inverter',
  ADMIN_CMS_COLLECTIONS: '/admin/cms/collections',
  ADMIN_CMS_COLLECTION: '/admin/cms/collections/:collection',
  ADMIN_STORE_ORDERS: '/admin/store-orders',
  ADMIN_STORE_ORDER_DETAIL: '/admin/store-orders/:id',

  // Dealer
  DEALER_DASHBOARD: '/dealer/dashboard',
  DEALER_DISPATCHES: '/dealer/dispatches',
  DEALER_DISPATCH_DETAIL: '/dealer/dispatches/:id',
  DEALER_GRN: '/dealer/grn',
  DEALER_GRN_DETAIL: '/dealer/grn/:id',
  DEALER_CUSTOMERS: '/dealer/customers',
  DEALER_CUSTOMER_DETAIL: '/dealer/customers/:id',
  DEALER_REPORTS: '/dealer/reports',
  DEALER_INVENTORY: '/dealer/inventory',
  DEALER_INVENTORY_DETAIL: '/dealer/inventory/:id',
  DEALER_BILLING: '/dealer/billing',
  DEALER_BILLING_NEW: '/dealer/billing/new',
  DEALER_SALES_QUICK: '/dealer/sales/quick',
  DEALER_BILLING_DETAIL: '/dealer/billing/:billId',
  DEALER_INVOICES: '/dealer/invoices',
  DEALER_INVOICE_DETAIL: '/dealer/invoices/:id',
  DEALER_WARRANTY: '/dealer/warranty',
  DEALER_WARRANTY_DETAIL: '/dealer/warranty/:id',
  DEALER_TEAM: '/dealer/team',
  DEALER_TEAM_PERFORMANCE: '/dealer/team/performance',

  // Employee
  EMPLOYEE_DASHBOARD: '/employee/dashboard',
  EMPLOYEE_DEALERS: '/employee/dealers',
  EMPLOYEE_DEALER_DETAIL: '/employee/dealers/:id',
  EMPLOYEE_DEALER_ANALYTICS: '/employee/dealer-analytics',
  EMPLOYEE_PERFORMANCE: '/employee/performance',
  EMPLOYEE_TASKS: '/employee/tasks',
  EMPLOYEE_TASK_DETAIL: '/employee/tasks/:id',
  EMPLOYEE_REPORTS: '/employee/reports',
  EMPLOYEE_REPORT_DETAIL: '/employee/reports/:id',
  EMPLOYEE_TEAM: '/employee/team',
  EMPLOYEE_APPROVALS: '/employee/approvals',
  EMPLOYEE_APPROVAL_DETAIL: '/employee/approvals/:id',

  // Service
  SERVICE_DASHBOARD: '/service/dashboard',
  SERVICE_TICKETS: '/service/tickets',
  SERVICE_TICKET_NEW: '/service/tickets/new',
  SERVICE_TICKET_DETAIL: '/service/tickets/:id',
  SERVICE_COMPLAINTS: '/service/complaints',
  SERVICE_COMPLAINT_NEW: '/service/complaints/new',
  SERVICE_COMPLAINT_DETAIL: '/service/complaints/:ticketId',
  SERVICE_SPARE_PARTS: '/service/spare-parts',
  SERVICE_SPARE_PARTS_DETAIL: '/service/spare-parts/:id',
  SERVICE_DEFECTIVE_RETURNS: '/service/defective-returns',
  SERVICE_DEFECTIVE_RETURNS_DETAIL: '/service/defective-returns/:id',

  // Customer
  CUSTOMER_DASHBOARD: '/customer/dashboard',
  CUSTOMER_PRODUCTS: '/customer/products',
  CUSTOMER_PRODUCT_DETAIL: '/customer/products/:id',
  CUSTOMER_ORDERS: '/customer/orders',
  CUSTOMER_ORDER_DETAIL: '/customer/orders/:id',
  CUSTOMER_WARRANTY: '/customer/warranty',
  CUSTOMER_WARRANTY_LOOKUP: '/customer/warranty/lookup',
  CUSTOMER_WARRANTY_DETAIL: '/customer/warranty/:id',
  CUSTOMER_SERVICE_REQUESTS: '/customer/service-requests',
  CUSTOMER_SERVICE_REQUEST_NEW: '/customer/service-requests/new',
  CUSTOMER_SERVICE_REQUEST_DETAIL: '/customer/service-requests/:id',

  // Public customer portal (no login)
  CUSTOMER_ACCESS: '/customer/access',
  CUSTOMER_ACCESS_HUB: '/customer/access/hub',
  CUSTOMER_ACCESS_PRODUCTS: '/customer/access/products',

  // Public (no login)
  LANDING: '/landing',
  PUBLIC_COMPLAINT: '/support/complaint',
  PUBLIC_WARRANTY_CHECK: '/warranty/check',

  // Shared
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '/not-found',
  MAINTENANCE: '/maintenance',
  SERVER_ERROR: '/server-error',
};
