/** Measuring units for catalog items (label + code). */
export const UNITS_OF_MEASURE = [
  { code: 'G NEX', label: 'Aaaaaaaaaaa(G NEX)' },
  { code: 'ANA', label: 'Aana(ANA)' },
  { code: 'ACS', label: 'Accessories (ACS)' },
  { code: 'AC', label: 'Acre(AC)' },
  { code: 'ADL', label: 'Adult(ADL)' },
  { code: 'AMP', label: 'Ampoule(AMP)' },
  { code: 'BAG', label: 'Bags(BAG)' },
  { code: 'BAL', label: 'Bale(BAL)' },
  { code: 'BALL', label: 'Balls(BALL)' },
  { code: 'BAR', label: 'Barni(BAR)' },
  { code: 'BRL', label: 'Barrel(BRL)' },
  { code: 'BTH', label: 'Batch(BTH)' },
  { code: 'BOU', label: 'Billions Of Units(BOU)' },
  { code: 'BLISTER', label: 'Blister(BLISTER)' },
  { code: 'BOLUS', label: 'Bolus(BOLUS)' },
  { code: 'BK', label: 'Book(BK)' },
  { code: 'BOR', label: 'Bora(BOR)' },
  { code: 'BTL', label: 'Bottles(BTL)' },
  { code: 'BOX', label: 'Box(BOX)' },
  { code: 'BRASS', label: 'Brass(BRASS)' },
  { code: 'BRICK', label: 'Brick(BRICK)' },
  { code: 'BCK', label: 'Buckets(BCK)' },
  { code: 'BKL', label: 'Buckles(BKL)' },
  { code: 'BUN', label: 'Bunches(BUN)' },
  { code: 'BDL', label: 'Bundles(BDL)' },
  { code: 'BTS', label: 'Butts(BTS)' },
  { code: 'CBL', label: 'Cable(CBL)' },
  { code: 'CAN', label: 'Cans(CAN)' },
  { code: 'CAP', label: 'Cap(CAP)' },
  { code: 'CPS', label: 'Capsules(CPS)' },
  { code: 'CT', label: 'Carat(CT)' },
  { code: 'CTS', label: 'Carats(CTS)' },
  { code: 'CARD', label: 'Card(CARD)' },
  { code: 'CTN', label: 'Cartons(CTN)' },
  { code: 'CART', label: 'Cartridge(CART)' },
  { code: 'CASE', label: 'Case(CASE)' },
  { code: 'CMS', label: 'Centimeter(CMS)' },
  { code: 'CNT', label: 'Cents(CNT)' },
  { code: 'CHAIN', label: 'Ch(CHAIN)' },
  { code: 'CHN', label: 'Chain(CHN)' },
  { code: 'CLD', label: 'Child(CLD)' },
  { code: 'CHOKA', label: 'Choka(CHOKA)' },
  { code: 'CHUDI', label: 'Chudi(CHUDI)' },
  { code: 'CLT', label: 'Cloth(CLT)' },
  { code: 'COIL', label: 'Coil(COIL)' },
  { code: 'CN', label: 'Cone(CN)' },
  { code: 'CONT', label: 'Container(CONT)' },
  { code: 'COPY', label: 'Copy(COPY)' },
  { code: 'COTT', label: 'Cotton(COTT)' },
  { code: 'COURSE', label: 'Course(COURSE)' },
  { code: 'CRT', label: 'Crate(CRT)' },
  { code: 'CRM', label: 'Cream(CRM)' },
  { code: 'CCM', label: 'Cubic Centimeter(CCM)' },
  { code: 'CUFT', label: 'Cubic Feet(CUFT)' },
  { code: 'CFM', label: 'Cubic Feet Per Minute(CFM)' },
  { code: 'CFT', label: 'Cubic Foot(CFT)' },
  { code: 'CBM', label: 'Cubic Meter(CBM)' },
  { code: 'CUM', label: 'Cubic Meters(CUM)' },
  { code: 'CUP', label: 'Cup(CUP)' },
  { code: 'CV', label: 'Cv(CV)' },
  { code: 'DAILY', label: 'Daily(DAILY)' },
  { code: 'DANGLER', label: 'Dangler(DANGLER)' },
  { code: 'DAY', label: 'Days(DAY)' },
  { code: 'DEZ', label: 'Daze(DEZ)' },
  { code: 'DMTR', label: 'Decimeter(DMTR)' },
  { code: 'DOZ', label: 'Dozen(DOZ)' },
  { code: 'DROP', label: 'Drop(DROP)' },
  { code: 'DRM', label: 'Drum(DRM)' },
  { code: 'DUTY', label: 'Duty(DUTY)' },
  { code: 'EA', label: 'Ea(EA)' },
  { code: 'EACH', label: 'Each(EACH)' },
  { code: 'FT', label: 'Feet(FT)' },
  { code: 'FT2', label: 'Feet Square(FT2)' },
  { code: 'FNGR', label: 'Finger(FNGR)' },
  { code: 'FIT', label: 'Fit(FIT)' },
  { code: 'FLT', label: 'Flat(FLT)' },
  { code: 'FLD', label: 'Fold(FLD)' },
  { code: 'FN', label: 'Fortnight(FN)' },
  { code: 'FREE', label: 'Free(FREE)' },
  { code: 'FTS', label: 'Fts(FTS)' },
  { code: 'FP', label: 'Full Plate(FP)' },
  { code: 'GEL', label: 'Gel(GEL)' },
  { code: 'GLS', label: 'Glasses(GLS)' },
  { code: 'GMS', label: 'Grams(GMS)' },
  { code: 'GGR', label: 'Great Gross(GGR)' },
  { code: 'GRS', label: 'Gross(GRS)' },
  { code: 'GYD', label: 'Gross Yards(GYD)' },
  { code: 'HF', label: 'Half(HF)' },
  { code: 'H.P.', label: 'Half Plate(H.P.)' },
  { code: 'HEGAR', label: 'Hanger(HEGAR)' },
  { code: 'HANGER', label: 'Hangers(HANGER)' },
  { code: 'HA', label: 'Hectare(HA)' },
  { code: 'HMT', label: 'Helmet(HMT)' },
  { code: 'HP', label: 'Horsepower(HP)' },
  { code: 'HRS', label: 'Hours(HRS)' },
  { code: 'HDS', label: 'Hundreds(HDS)' },
  { code: 'IJN', label: 'Ijn(INJECTION)' },
  { code: 'IN', label: 'Inches(IN)' },
  { code: 'INJECTION', label: 'Inj(INJECTION)' },
  { code: 'INS', label: 'Insertion(INS)' },
  { code: 'ITEM ID', label: 'Item Id(ITEM ID)' },
  { code: 'JAR', label: 'Jars(JAR)' },
  { code: 'JL', label: 'Jhal(JL)' },
  { code: 'JO', label: 'Jhola(JO)' },
  { code: 'JHL', label: 'Jhola Jhal(JHL)' },
  { code: 'JHD', label: 'Jhudi(JHD)' },
  { code: 'JOB', label: 'Job(JOB)' },
  { code: 'KT', label: 'Katta(KT)' },
  { code: 'KGS', label: 'Kilograms(KGS)' },
  { code: 'KLR', label: 'Kiloliter(KLR)' },
  { code: 'KME', label: 'Kilometre(KME)' },
  { code: 'KMS', label: 'Kilometres(KMS)' },
  { code: 'KVA', label: 'Kilovolt-amp(KVA)' },
  { code: 'KW', label: 'Kilowatt(KW)' },
  { code: 'KIT', label: 'Kit(KIT)' },
  { code: 'KM', label: 'Km(KM)' },
  { code: 'LAD', label: 'Ladi(LAD)' },
  { code: 'LENG', label: 'Length(LENG)' },
  { code: 'LBS', label: 'Libra Pondo(LBS)' },
  { code: 'LNE', label: 'Line(LNE)' },
  { code: 'LTR', label: 'Litre(LTR)' },
  { code: 'LOT', label: 'Lot(LOT)' },
  { code: 'LS', label: 'Lump Sum (LS)' },
  { code: 'MILLE', label: 'M(MILLE)' },
  { code: 'MAN-DAY', label: 'Man-days(MAN-DAY)' },
  { code: 'MK', label: 'Marakkal(MK)' },
  { code: 'MRK', label: 'Mark(MRK)' },
  { code: 'MBPS', label: 'Mbps(MBPS)' },
  { code: 'MW', label: 'Megawatt(MW)' },
  { code: 'MTR', label: 'Meters(MTR)' },
  { code: 'MMBTU', label: 'Metric Million British Thermal Unit(MMBTU)' },
  { code: 'MTON', label: 'Metric Ton(MTON)' },
  { code: 'MTS', label: 'Metric, Ton(MTS)' },
  { code: 'UG', label: 'Microgram(UG)' },
  { code: 'M', label: 'Mille(M)' },
  { code: 'M/C', label: 'Millicoulomb(M/C)' },
  { code: 'MLG', label: 'Milligram(MLG)' },
  { code: 'MLT', label: 'Millilitre(MLT)' },
  { code: 'MM', label: 'Millimeter(MM)' },
  { code: 'MINS', label: 'Minutes(MINS)' },
  { code: 'UOM', label: 'Month (UOM)' },
  { code: 'MON', label: 'Months(MON)' },
  { code: 'MORA', label: 'Mora(MORA)' },
  { code: 'NIGHT', label: 'Nights(NIGHT)' },
  { code: 'NON', label: 'Non.(NON)' },
  { code: 'NONE', label: 'None(NONE)' },
  { code: 'NOS', label: 'Numbers(NOS)' },
  { code: 'OINT', label: 'Ointment(OINT)' },
  { code: 'OTH', label: 'Others(OTH)' },
  { code: 'OR', label: 'Outer(OR)' },
  { code: 'PKG', label: 'Package(PKG)' },
  { code: 'PKT', label: 'Packets(PKT)' },
  { code: 'PAC', label: 'Packs(PAC)' },
  { code: 'PAD', label: 'Pad(PAD)' },
  { code: 'PADS', label: 'Pads(PADS)' },
  { code: 'PAGE', label: 'Pages(PAGE)' },
  { code: 'PAIR', label: 'Pair(PAIR)' },
  { code: 'PRS', label: 'Pairs(PRS)' },
  { code: 'PNL', label: 'Panel(PNL)' },
  { code: 'PART', label: 'Part(PART)' },
  { code: 'PATTA', label: 'Patta(PATTA)' },
  { code: 'PTI', label: 'Patti(PTI)' },
  { code: 'PAX', label: 'Pax(PAX)' },
  { code: 'PER', label: 'Per(PER)' },
  { code: '/DAY', label: 'Per Day(/DAY)' },
  { code: 'PMT', label: 'Per Metric Ton(PMT)' },
  { code: 'PER TRAINER', label: 'Per Trainer(PER TRAINER)' },
  { code: 'PWP', label: 'Per Watt Peak(PWP)' },
  { code: 'PERSON', label: 'Persons(PERSON)' },
  { code: 'PET', label: 'Peti(PET)' },
  { code: 'PHILE', label: 'Phile(PHILE)' },
  { code: 'PCS', label: 'Pieces(PCS)' },
  { code: 'PIPE', label: 'Pipe(PIPE)' },
  { code: 'PLT', label: 'Plates(PLT)' },
  { code: 'PCKT', label: 'Pocket(PCKT)' },
  { code: 'PT', label: 'Point(PT)' },
  { code: 'PRT', label: 'Portion(PRT)' },
  { code: 'POCH', label: 'Pouch(POCH)' },
  { code: 'POUND', label: 'Pound(POUND)' },
  { code: 'PD', label: 'Puda(PD)' },
  { code: 'QUAD', label: 'Quad(QUAD)' },
  { code: 'QTY', label: 'Quantity(QTY)' },
  { code: 'QT', label: 'Quarter(QT)' },
  { code: 'QTL', label: 'Quintal(QTL)' },
  { code: 'RTI', label: 'Ratti(RTI)' },
  { code: 'REAM', label: 'Ream(REAM)' },
  { code: 'REEL', label: 'Reel(REEL)' },
  { code: 'RESP', label: 'Respules(RESP)' },
  { code: 'RIM', label: 'Rim(RIM)' },
  { code: 'ROL', label: 'Rolls(ROL)' },
  { code: 'ROOM', label: 'Room(ROOM)' },
  { code: 'RFT', label: 'Running Foot(RFT)' },
  { code: 'RMT', label: 'Running Meter(RMT)' },
  { code: 'RS', label: 'Rupees(RS)' },
  { code: 'SAC', label: 'Sachet(SAC)' },
  { code: 'SEC', label: 'Seconds(SEC)' },
  { code: 'SEM', label: 'Semester(SEM)' },
  { code: 'SERVICE', label: 'Service(SERVICE)' },
  { code: 'SSN', label: 'Session(SSN)' },
  { code: 'SET', label: 'Sets(SET)' },
  { code: 'SHEET', label: 'Sheet(SHEET)' },
  { code: 'SKINS', label: 'Skins(SKINS)' },
  { code: 'SLT', label: 'Slants(SLT)' },
  { code: 'SLEVES', label: 'Sleves(SLEVES)' },
  { code: 'SPLS', label: 'Spindles(SPLS)' },
  { code: 'SPRAY', label: 'Spray(SPRAY)' },
  { code: 'SQCM', label: 'Square Centimeters(SQCM)' },
  { code: 'SQF', label: 'Square Feet(SQF)' },
  { code: 'GAJ', label: 'Square Gaj(GAJ)' },
  { code: 'GAZ', label: 'Square Gaz(GAZ)' },
  { code: 'SQIN', label: 'Square Inches(SQIN)' },
  { code: 'SQ KM', label: 'Square Kilometer(SQ KM)' },
  { code: 'SQM', label: 'Square Meters(SQM)' },
  { code: 'SQY', label: 'Square Yards(SQY)' },
  { code: 'SARAM', label: 'Srm(SARAM)' },
  { code: 'ST POUCH', label: 'Std Pouch(ST POUCH)' },
  { code: 'STICKER', label: 'Stickers(STICKER)' },
  { code: 'STONE', label: 'Stone(STONE)' },
  { code: 'STRP', label: 'Strips(STRP)' },
  { code: 'SYRP', label: 'Syrup(SYRP)' },
  { code: 'TBS', label: 'Tablets(TBS)' },
  { code: 'TGM', label: 'Ten Gross(TGM)' },
  { code: 'TEST', label: 'Test(TEST)' },
  { code: 'TN', label: 'Than(TN)' },
  { code: 'THD', label: 'Thousands(THD)' },
  { code: 'TKT', label: 'Ticket(TKT)' },
  { code: 'TIN', label: 'Tin(TIN)' },
  { code: 'TON', label: 'Tonnes(TON)' },
  { code: 'TRY', label: 'Trays(TRY)' },
  { code: 'TRLY', label: 'Trolly(TRLY)' },
  { code: 'TRIP', label: 'Trp(TRIP)' },
  { code: 'TRK', label: 'Truck(TRK)' },
  { code: 'TUB', label: 'Tubes(TUB)' },
  { code: 'UNT', label: 'Units(UNT)' },
  { code: 'UGS', label: 'Us Gallons(UGS)' },
  { code: 'VIAL', label: 'Vials(VIAL)' },
  { code: 'W', label: 'Watt(W)' },
  { code: 'WEEK', label: 'Weeks(WEEK)' },
  { code: 'YDS', label: 'Yards(YDS)' },
  { code: 'YRS', label: 'Years(YRS)' },
];

export const DEFAULT_UNIT_OF_MEASURE = 'PCS';

/** Map legacy catalog values to current codes */
export const LEGACY_UOM_MAP = {
  Piece: 'PCS',
  Pieces: 'PCS',
  Box: 'BOX',
  Set: 'SET',
  Sets: 'SET',
  Kit: 'KIT',
};

export function normalizeUnitOfMeasure(value) {
  if (!value) return DEFAULT_UNIT_OF_MEASURE;
  if (LEGACY_UOM_MAP[value]) return LEGACY_UOM_MAP[value];
  const found = UNITS_OF_MEASURE.find((u) => u.code === value || u.label === value);
  return found?.code || value;
}

export function getUnitLabel(code) {
  const normalized = normalizeUnitOfMeasure(code);
  return UNITS_OF_MEASURE.find((u) => u.code === normalized)?.label || normalized;
}
