/** All granular permissions available in the system. */
export const PERMISSION_CATALOG = [
  { key: 'analytics.read', label: 'View Analytics', module: 'Analytics' },
  { key: 'warehouses.read', label: 'View Warehouses', module: 'Warehouses' },
  { key: 'warehouses.create', label: 'Create Warehouses', module: 'Warehouses' },
  { key: 'warehouses.update', label: 'Update Warehouses', module: 'Warehouses' },
  { key: 'inventory.read', label: 'View Inventory', module: 'Inventory' },
  { key: 'inventory.create', label: 'Create Inventory', module: 'Inventory' },
  { key: 'inventory.update', label: 'Update Inventory', module: 'Inventory' },
  { key: 'inventory.delete', label: 'Delete Inventory', module: 'Inventory' },
  { key: 'inventory.export', label: 'Export Inventory', module: 'Inventory' },
  { key: 'grn.read', label: 'View GRN', module: 'GRN' },
  { key: 'grn.create', label: 'Create GRN', module: 'GRN' },
  { key: 'grn.verify', label: 'Verify GRN', module: 'GRN' },
  { key: 'dispatch.read', label: 'View Dispatch', module: 'Dispatch' },
  { key: 'dispatch.create', label: 'Create Dispatch', module: 'Dispatch' },
  { key: 'dispatch.update', label: 'Update Dispatch', module: 'Dispatch' },
  { key: 'dealers.read', label: 'View Dealers', module: 'Dealers' },
  { key: 'dealers.create', label: 'Create Dealers', module: 'Dealers' },
  { key: 'dealers.update', label: 'Update Dealers', module: 'Dealers' },
  { key: 'employees.read', label: 'View Employees', module: 'Employees' },
  { key: 'employees.create', label: 'Create Employees', module: 'Employees' },
  { key: 'employees.update', label: 'Update Employees', module: 'Employees' },
  { key: 'products.read', label: 'View Products', module: 'Products' },
  { key: 'products.create', label: 'Create Products', module: 'Products' },
  { key: 'products.update', label: 'Update Products', module: 'Products' },
  { key: 'categories.read', label: 'View Categories', module: 'Catalog' },
  { key: 'categories.create', label: 'Create Categories', module: 'Catalog' },
  { key: 'brands.read', label: 'View Brands', module: 'Catalog' },
  { key: 'brands.create', label: 'Create Brands', module: 'Catalog' },
  { key: 'pricing.read', label: 'View Pricing', module: 'Pricing' },
  { key: 'pricing.update', label: 'Update Pricing', module: 'Pricing' },
  { key: 'expenses.read', label: 'View Expenses', module: 'Expenses' },
  { key: 'expenses.create', label: 'Create Expenses', module: 'Expenses' },
  { key: 'notifications.read', label: 'View Notifications', module: 'Notifications' },
  { key: 'billing.read', label: 'View Billing', module: 'Billing' },
  { key: 'billing.create', label: 'Create Bills', module: 'Billing' },
  { key: 'billing.update', label: 'Update Bills', module: 'Billing' },
  { key: 'billing.send', label: 'Send Bills', module: 'Billing' },
  { key: 'invoices.read', label: 'View Invoices', module: 'Invoices' },
  { key: 'invoices.export', label: 'Export Invoices', module: 'Invoices' },
  { key: 'warranty.read', label: 'View Warranty', module: 'Warranty' },
  { key: 'warranty.create', label: 'Create Warranty', module: 'Warranty' },
  { key: 'complaints.read', label: 'View Complaints', module: 'Service' },
  { key: 'complaints.create', label: 'Create Complaints', module: 'Service' },
  { key: 'complaints.update', label: 'Update Complaints', module: 'Service' },
  { key: 'complaints.escalate', label: 'Escalate Complaints', module: 'Service' },
  { key: 'spares.read', label: 'View Spares', module: 'Service' },
  { key: 'spares.request', label: 'Request Spares', module: 'Service' },
  { key: 'returns.read', label: 'View Returns', module: 'Service' },
  { key: 'returns.create', label: 'Create Returns', module: 'Service' },
  { key: 'tasks.read', label: 'View Tasks', module: 'Tasks' },
  { key: 'tasks.update', label: 'Update Tasks', module: 'Tasks' },
  { key: 'approvals.read', label: 'View Approvals', module: 'Approvals' },
  { key: 'approvals.update', label: 'Review Approvals', module: 'Approvals' },
  { key: 'reports.read', label: 'View Reports', module: 'Reports' },
  { key: 'team.read', label: 'View Team', module: 'Team' },
  { key: 'employee.dealers.read', label: 'View Assigned Dealers', module: 'Employee' },
  { key: 'employee.analytics.read', label: 'View Dealer Analytics', module: 'Employee' },
  { key: 'employee.performance.read', label: 'View Performance', module: 'Employee' },
  { key: 'dealer.dashboard', label: 'Dealer Dashboard', module: 'Dealer' },
  { key: 'dealer.inventory.read', label: 'Dealer Inventory', module: 'Dealer' },
  { key: 'dealer.team.read', label: 'Dealer Team', module: 'Dealer' },
  { key: 'dealer.customers.read', label: 'Dealer Customers', module: 'Dealer' },
  { key: 'dealer.customers.create', label: 'Create Customers', module: 'Dealer' },
  { key: 'dealer.dispatch.read', label: 'Dealer Dispatches', module: 'Dealer' },
  { key: 'dealer.grn.read', label: 'Dealer GRN', module: 'Dealer' },
  { key: 'dealer.reports.read', label: 'Dealer Reports', module: 'Dealer' },
  { key: 'service.dashboard', label: 'Service Dashboard', module: 'Service' },
  { key: 'orders.read', label: 'View Orders', module: 'Customer' },
  { key: 'service-requests.read', label: 'View Service Requests', module: 'Customer' },
  { key: 'service-requests.create', label: 'Create Service Requests', module: 'Customer' },
  { key: 'settings.read', label: 'View Settings', module: 'Settings' },
  { key: 'settings.update', label: 'Update Settings', module: 'Settings' },
  { key: 'audit.read', label: 'View Audit Logs', module: 'Audit' },
  { key: 'gst.config', label: 'GST Configuration', module: 'GST' },
  { key: 'rbac.read', label: 'View Roles & Permissions', module: 'RBAC' },
  { key: 'rbac.update', label: 'Manage Roles & Permissions', module: 'RBAC' },
];

export const ALL_PERMISSION_KEYS = PERMISSION_CATALOG.map((p) => p.key);
