/** Keep in sync with frontend/src/config/permissions.config.js */
export const ROLE_PERMISSIONS = {
  MASTER_ADMIN: [
    'analytics.read', 'warehouses.read', 'warehouses.create', 'warehouses.update',
    'inventory.read', 'inventory.create', 'inventory.update', 'inventory.delete', 'inventory.export',
    'grn.read', 'grn.create', 'grn.verify',
    'dispatch.read', 'dispatch.create', 'dispatch.update',
    'dealers.read', 'dealers.create', 'dealers.update',
    'employees.read', 'employees.create', 'employees.update',
    'products.read', 'products.create', 'products.update',
    'categories.read', 'categories.create',
    'brands.read', 'brands.create',
    'parties.read', 'parties.create', 'parties.update',
    'purchases.read', 'purchases.create', 'purchases.receive',
    'pricing.read', 'pricing.update',
    'expenses.read', 'expenses.create',
    'notifications.read',
    'billing.read', 'billing.create', 'billing.update', 'billing.send',
    'invoices.read', 'invoices.export',
    'warranty.read', 'warranty.create',
    'complaints.read', 'complaints.create', 'complaints.update', 'complaints.escalate',
    'spares.read', 'spares.request',
    'returns.read', 'returns.create',
    'tasks.read', 'tasks.update',
    'approvals.read', 'approvals.update',
    'reports.read', 'team.read',
    'employee.dealers.read', 'employee.analytics.read', 'employee.performance.read',
    'dealer.dashboard', 'dealer.inventory.read', 'dealer.team.read',
    'dealer.customers.read', 'dealer.customers.create',
    'dealer.dispatch.read', 'dealer.grn.read', 'dealer.reports.read',
    'service.dashboard',
    'orders.read', 'service-requests.read', 'service-requests.create',
    'settings.read', 'settings.update', 'audit.read', 'gst.config',
    'rbac.read', 'rbac.update',
    'cms.read', 'cms.create', 'cms.update', 'cms.delete', 'cms.publish',
    'store.orders.read', 'store.orders.update', 'store.analytics.read',
  ],
  WAREHOUSE_MANAGER: [
    'analytics.read', 'warehouses.read', 'notifications.read',
    'inventory.read', 'inventory.create', 'inventory.update',
    'grn.read', 'grn.create', 'grn.verify',
    'parties.read', 'parties.create', 'parties.update',
    'purchases.read', 'purchases.create', 'purchases.receive',
    'dispatch.read', 'dispatch.create', 'dispatch.update',
    'spares.read', 'returns.read',
  ],
  DEALER_ADMIN: [
    'dealer.dashboard', 'dealer.inventory.read', 'dealer.dispatch.read', 'dealer.grn.read',
    'dealer.customers.read', 'dealer.customers.create', 'notifications.read',
    'billing.read', 'billing.create', 'billing.update', 'billing.send',
    'invoices.read', 'warranty.read', 'dealer.team.read', 'dealer.reports.read',
  ],
  DEALER_SALES: [
    'dealer.inventory.read', 'dealer.dispatch.read', 'dealer.grn.read', 'notifications.read',
    'dealer.customers.read', 'dealer.customers.create',
    'billing.read', 'billing.create', 'billing.send',
    'invoices.read', 'warranty.read', 'dealer.reports.read',
  ],
  EMPLOYEE: [
    'tasks.read', 'tasks.update', 'reports.read', 'notifications.read',
    'employee.dealers.read', 'employee.analytics.read', 'employee.performance.read',
  ],
  MANAGER: [
    'tasks.read', 'tasks.update', 'reports.read', 'team.read', 'notifications.read',
    'approvals.read', 'approvals.update',
    'employee.dealers.read', 'employee.analytics.read', 'employee.performance.read',
  ],
  CUSTOMER_SUPPORT: [
    'service.dashboard', 'notifications.read',
    'service-requests.read', 'service-requests.create',
    'complaints.read', 'complaints.create', 'complaints.update', 'complaints.escalate',
  ],
  SERVICE_CENTER: [
    'service.dashboard', 'notifications.read',
    'service-requests.read', 'service-requests.create',
    'complaints.read', 'complaints.update',
    'spares.read', 'spares.request',
    'returns.read', 'returns.create',
  ],
  CUSTOMER: [
    'orders.read', 'warranty.read', 'service-requests.read', 'service-requests.create', 'notifications.read',
  ],
};
