import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Search, ShoppingBag } from 'lucide-react';
import { PageShell } from '@/components/layout/PageShell';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { LoadingState } from '@/components/feedback/LoadingState';
import { EmptyState } from '@/components/feedback/EmptyState';
import { salesInvoicesService } from '@/services/sales-invoices.service';
import { queryKeys } from '@/services/api/queryKeys';
import { useAuth } from '@/hooks/useAuth';
import { formatCurrency } from '@/utils/format';

function Badge({ status }) {
  const map = {
    DRAFT: 'bg-amber-100 text-amber-700',
    SENT: 'bg-blue-100 text-blue-700',
    PAID: 'bg-green-100 text-green-700',
    CANCELLED: 'bg-red-100 text-red-700',
  };
  return <span className={`inline-block rounded-full px-2 py-0.5 text-xs font-semibold ${map[status] || 'bg-surface-2'}`}>{status}</span>;
}

function fmtDate(d) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

export default function DealerPurchaseListPage() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [search, setSearch] = useState('');

  const filters = {
    dealerId: user?.dealerId || undefined,
    search: search || undefined,
    status: 'SENT', // Dealer should see sent/finalized invoices
    perPage: 50,
  };

  const { data, isLoading } = useQuery({
    queryKey: queryKeys.salesInvoices.list(filters),
    queryFn: () => salesInvoicesService.getList(filters),
    enabled: !!user?.dealerId,
  });

  const invoices = data?.data || [];

  return (
    <PageShell
      title="My Purchases"
      subtitle="Invoices generated by company admin for your orders"
    >
      <div className="flex flex-wrap gap-3 mb-4">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--color-text-tertiary)]" />
          <Input className="w-64 pl-9" placeholder="Search by invoice number…" value={search} onChange={(e) => setSearch(e.target.value)} />
        </div>
      </div>

      {isLoading ? <LoadingState message="Loading purchases…" /> : invoices.length === 0 ? (
        <EmptyState
          icon={ShoppingBag}
          title="No purchase invoices"
          description="Invoices billed to your dealer account will appear here"
        />
      ) : (
        <Card>
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b bg-surface-2 text-left text-xs uppercase text-[var(--color-text-secondary)]">
                    <th className="px-4 py-3">Invoice No</th>
                    <th className="px-4 py-3">Date</th>
                    <th className="px-4 py-3">Due Date</th>
                    <th className="px-4 py-3 text-right">Total Amount</th>
                    <th className="px-4 py-3 text-right">Balance Due</th>
                    <th className="px-4 py-3">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {invoices.map((inv) => (
                    <tr key={inv.id} className="border-b border-surface-3 hover:bg-surface-2 cursor-pointer" onClick={() => navigate(`/dealer/purchases/${inv.id}`)}>
                      <td className="px-4 py-3 font-mono font-semibold text-brand-600">{inv.invoiceNo}</td>
                      <td className="px-4 py-3 text-[var(--color-text-secondary)]">{fmtDate(inv.invoiceDate)}</td>
                      <td className="px-4 py-3 text-[var(--color-text-secondary)]">{fmtDate(inv.dueDate)}</td>
                      <td className="px-4 py-3 text-right tabular-nums font-semibold">{formatCurrency(inv.total)}</td>
                      <td className="px-4 py-3 text-right tabular-nums text-red-600">{inv.balanceAmount > 0 ? formatCurrency(inv.balanceAmount) : '—'}</td>
                      <td className="px-4 py-3"><Badge status={inv.status} /></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}
    </PageShell>
  );
}
